### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by ghost** [RichardVasquez/kses#1]
Just found your repo on here, and wanted to say thank you for creating the kses project, and taking it back up again. Your project has been a life saver for many people, and sites over the years.

I'm currently using a modified (I minified, and included html5 cleaning) in my own project, LibreCMS.

**Comment by RichardVasquez** [comment]
Glad to hear it's been useful for you.  I will probably be taking a look at the whole thing this holiday timeframe to get a better feel for what I wrote all those years ago.
