### ISSUE TITLE
oop php 5 "Undefined variable: string2"

### ISSUE THREAD

**Issue by vatnoise** [RichardVasquez/kses#2]
Hi,
Decided to give this class a try and after using parse on an "a" tag that has a "href" attribute with http link it gives me an error:

`Notice: Undefined variable: string2 in /*****/php5.class.kses.php on line 958`

I'm I right to assume that that $string2 should be $string?

**Comment by LinusU** [comment]
Having the same issue.

ping @RichardVasquez ☺️
