### ISSUE TITLE
Not Working in PHP 7

### ISSUE THREAD

**Issue by sakmbd** [RichardVasquez/kses#4]
Warning:  preg_replace_callback(): Requires argument 2, 'kses_normalize_entities2("\1")', to be a valid callback in F:\xampp\htdocs\XSS\kses-master\kses.php on line 522

Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in F:\xampp\htdocs\XSS\kses-master\kses.php on line 81

**Comment by RichardVasquez** [comment]
I'm not doing a lot of PHP these days. If you have a PR for it, I'll test it and merge it in.

**Comment by LinusU** [comment]
should be fixed by #6
